name: appform
description: App Form library for form validation with Formz
version: 1.0.0
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl:

  formz: 0.4.1
  equatable:

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  test: ^1.17.11
  very_good_analysis: ^3.1.0